function Dec = BoundaryRandomReset(Dec, RandomDec, Prob)
% BoundaryRandomReset - Replace violated dimensions with supplied samples
%
% RandomDec is generated by the caller so existing random-number ordering
% and consumption remain unchanged.

%------------------------------- Copyright --------------------------------
% Copyright (c) Yanchi Li. You are free to use the MToP for research
% purposes. All publications which use this platform should acknowledge
% the use of MToP and cite as "Y. Li, W. Gong, T. Zhang, F. Ming,
% S. Li, Q. Gu, and Y.-S. Ong, MToP: A MATLAB Benchmarking Platform for
% Evolutionary Multitasking, ACM Trans. Evol. Learn. Optim., 2026"
%--------------------------------------------------------------------------

Dec = real(Dec);
RandomDec = real(RandomDec);
if nargin >= 3 && ~Prob.Bounded
    return;
end

vioUp = Dec > 1;
Dec(vioUp) = RandomDec(vioUp);
vioLow = Dec < 0;
Dec(vioLow) = RandomDec(vioLow);
end
